### ISSUE TITLE
WP LESS compiles on every pageload.

### ISSUE THREAD

**Issue by BoweFrankema** [oncletom/wp-less#89]
I am using WP LESS inside my plugin and for some reason the plugin compiles the entire stylesheet on every pageload. The files are generated and stored inside my uploads folder, but still the compiler runs every time. Here's my setup:
- Installed WP-LESS as a plugin
- Added the following to my plugin config:

```
define('WP_LESS_COMPILER', 'less.php');

function theme_enqueue_styles() {
    wp_enqueue_style('theme-main', plugin_dir_url( __FILE__ ) . '/assets/less/' . Kirki::get_option('wf_preset') . '.less');
}
add_action('init', 'theme_enqueue_styles');
```

The CSS files are stored in the following path:

```
/mysite-development/wp-content/uploads/wp-lesshttp:/development.wefoster.co/wp-content/plugins/wefoster-plus/assets/less
```

Any idea what might be happening?

**Comment by oncletom** [comment]
It seems it fails to find the cache file so it builds it every single time.

The CSS path does not look normal so I suppose this is the source of your problem.

**Comment by schnoggo** [comment]
Ah. I was just asking on another issue if anyone has tried enqueuing a .less file outside their theme, since it looks like the code would have a problem finding that.
Just so you know, @BoweFrankema , the issue is that wp_enqueue_style() takes a URI, but wp-less needs a local path so it can check modification dates and read the .less files using file_get_contents().

With different web server technologies, rewrite rules, and WordPress path settings, there's no 100% reliable way to map a URI to local path.

@oncletom, It seems like it would be possible use http get mod date and file content, right? Obviously that would have more overhead, but it would work in these non-standard situations.

**Comment by oncletom** [comment]
To be honest, I would not require an external CSS/LESS file as it is would slow down and potentially make your website vulnerable.

Better to curl/copy/bundle it before deploying your theme update. It is safer and makes your theme content immutable.

**Comment by pixelbart** [comment]
Closed, due to age. If the problem persists, please reopen the issue.
